# -*- coding: utf-8 -*-
"""nouha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10sA4PpNTWUDhHju2F6lgCDalU_gTugwi
"""

import numpy as np
import pandas as pd
from sklearn import linear_model
import math

!pip install word2number

from word2number import w2n

d=pd.read_csv("hiring.csv")
d

d['experience']=d['experience'].fillna("zero")

d

d.experience = d.experience.apply(w2n.word_to_num)

d

median_test_score=math.floor(d['test_score(out of 10)'].mean())

median_test_score

d['test_score(out of 10)'] = d['test_score(out of 10)'].fillna(median_test_score)
d

regression=linear_model.LinearRegression()
regression.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary($)'])

df1=pd.read_excel("/content/hiring_test (2).xlsx")

df1

df1.experience = df1.experience.apply(w2n.word_to_num)

df1

p=regression.predict(df1)
df1

df1['prices']=p
df1